reason: true
rerun-incomplete: true
keep-going: true
printshellcmds: true
local-cores: 4
jobs: 500
max-jobs-per-second: 1
use-conda: true
conda-frontend: mamba
latency-wait: 120
use-singularity: true
singularity-args: '--nv '
cluster: qsub -j y -cwd -V
              -A {resources.account}
              -q {resources.partition}
              -pe smp {threads}
              -o {resources.out}
              -e {resources.err} {resources.extra}
default-resources: 
  - account='$ACCOUNT'
  - partition='$PARTITION'
  - tmpdir=system_tmpdir
  - threads=1
  - out='./cluster_logs/sge-$JOB_NAME-$JOB_ID-$HOSTNAME.out'
  - err='./cluster_logs/sge-$JOB_NAME-$JOB_ID-$HOSTNAME.err'
  - extra=''
