reason: true
rerun-incomplete: true
keep-going: true
printshellcmds: true
local-cores: 4
max-threads: 256
jobs: 500
max-jobs-per-second: 1
use-conda: true
conda-frontend: mamba
latency-wait: 120
use-singularity: true
singularity-args: '--nv '
cluster: bsub -cwd 
              -q {resources.partition}
              -n {threads}
              -M {resources.mem_mb}
              -o {resources.out}
              -e {resources.err} {resources.extra}
default-resources: 
  - partition='$PARTITION'
  - tmpdir=system_tmpdir
  - threads=1
  - mem_mb=8000*threads
  - out='./cluster_logs/lsf-$LSB_JOBNAME-$LSB_JOBID-$HOSTNAME.out'
  - err='./cluster_logs/lsf-$LSB_JOBNAME-$LSB_JOBID-$HOSTNAME.err'
  - extra=''
