reason: true
rerun-incomplete: true
keep-going: true
jobs: 500
max-jobs-per-second: 1
use-conda: true
conda-frontend: mamba
latency-wait: 120
cluster: sbatch --account={resources.account}
                --partition={resources.partition}
                --cpus-per-task={threads}
                --output={resources.out} {resources.extra}
default-resources: 
  - account='100humans'
  - partition='compute'
  - tmpdir=system_tmpdir
  - threads=1
  - out='cluster_logs/slurm-%x-%j-%N.out'
  - extra=''